CREATE TABLE adherent (
  rowid int NOT NULL,
  ref varchar(30) NOT NULL,
  entity int NOT NULL DEFAULT '1',
  ref_ext varchar(128) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  civility varchar(6) DEFAULT NULL,
  lastname varchar(50) DEFAULT NULL,
  firstname varchar(50) DEFAULT NULL,
  login varchar(50) DEFAULT NULL,
  pass varchar(50) DEFAULT NULL,
  pass_crypted varchar(128) DEFAULT NULL,
  fk_adherent_type int NOT NULL,
  morphy varchar(3) NOT NULL,
  societe varchar(128) DEFAULT NULL,
  fk_soc int DEFAULT NULL,
  address text,
  zip varchar(30) DEFAULT NULL,
  town varchar(50) DEFAULT NULL,
  state_id int DEFAULT NULL,
  country int DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  socialnetworks text,
  skype varchar(255) DEFAULT NULL,
  twitter varchar(255) DEFAULT NULL,
  facebook varchar(255) DEFAULT NULL,
  linkedin varchar(255) DEFAULT NULL,
  instagram varchar(255) DEFAULT NULL,
  snapchat varchar(255) DEFAULT NULL,
  googleplus varchar(255) DEFAULT NULL,
  youtube varchar(255) DEFAULT NULL,
  whatsapp varchar(255) DEFAULT NULL,
  phone varchar(30) DEFAULT NULL,
  phone_perso varchar(30) DEFAULT NULL,
  phone_mobile varchar(30) DEFAULT NULL,
  birth date DEFAULT NULL,
  photo varchar(255) DEFAULT NULL,
  statut int NOT NULL DEFAULT '0',
  public_k int NOT NULL DEFAULT '0',
  datefin datetime DEFAULT NULL,
  note_private text,
  note_public text,
  model_pdf varchar(255) DEFAULT NULL,
  datevalid datetime DEFAULT NULL,
  datec datetime DEFAULT NULL,
  tms timestamp NOT NULL,
  fk_user_author int DEFAULT NULL,
  fk_user_mod int DEFAULT NULL,
  fk_user_valid int DEFAULT NULL,
  canvas varchar(32) DEFAULT NULL,
  import_key varchar(14) DEFAULT NULL,
  PRIMARY KEY (rowid),
  CONSTRAINT uk_adherent_ref UNIQUE(ref,entity),
  CONSTRAINT uk_adherent_login UNIQUE(login,entity),
  CONSTRAINT uk_adherent_fk_soc UNIQUE(fk_soc),
  CONSTRAINT idx_adherent_fk_adherent_type UNIQUE(fk_adherent_type),
  CONSTRAINT adherent_fk_soc FOREIGN KEY (fk_soc) REFERENCES dbo.societe (rowid),
  CONSTRAINT fk_adherent_adherent_type FOREIGN KEY (fk_adherent_type) REFERENCES dbo.adherent_type (rowid)
)