CREATE TABLE societe (
  rowid int NOT NULL,
  nom varchar(128) DEFAULT NULL,
  name_alias varchar(128) DEFAULT NULL,
  entity int NOT NULL DEFAULT '1',
  ref_ext varchar(255) DEFAULT NULL,
  ref_int varchar(255) DEFAULT NULL,
  statut int DEFAULT '0',
  parent int DEFAULT NULL,
  status int DEFAULT '1',
  code_client varchar(24) DEFAULT NULL,
  code_fournisseur varchar(24) DEFAULT NULL,
  code_compta varchar(24) DEFAULT NULL,
  code_compta_fournisseur varchar(24) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  zip varchar(25) DEFAULT NULL,
  town varchar(50) DEFAULT NULL,
  fk_departement int DEFAULT '0',
  fk_pays int DEFAULT '0',
  fk_account int DEFAULT '0',
  phone varchar(20) DEFAULT NULL,
  fax varchar(20) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  email varchar(128) DEFAULT NULL,
  socialnetworks text,
  skype varchar(255) DEFAULT NULL,
  twitter varchar(255) DEFAULT NULL,
  facebook varchar(255) DEFAULT NULL,
  linkedin varchar(255) DEFAULT NULL,
  instagram varchar(255) DEFAULT NULL,
  snapchat varchar(255) DEFAULT NULL,
  googleplus varchar(255) DEFAULT NULL,
  youtube varchar(255) DEFAULT NULL,
  whatsapp varchar(255) DEFAULT NULL,
  fk_effectif int DEFAULT '0',
  fk_typent int DEFAULT NULL,
  fk_forme_juridique int DEFAULT '0',
  fk_currency varchar(3) DEFAULT NULL,
  siren varchar(128) DEFAULT NULL,
  siret varchar(128) DEFAULT NULL,
  ape varchar(128) DEFAULT NULL,
  idprof4 varchar(128) DEFAULT NULL,
  idprof5 varchar(128) DEFAULT NULL,
  idprof6 varchar(128) DEFAULT NULL,
  tva_intra varchar(20) DEFAULT NULL,
  capital float DEFAULT NULL,
  fk_stcomm int NOT NULL DEFAULT '0',
  note_private text,
  note_public text,
  model_pdf varchar(255) DEFAULT NULL,
  prefix_comm varchar(5) DEFAULT NULL,
  client int DEFAULT '0',
  fournisseur int DEFAULT '0',
  supplier_account varchar(32) DEFAULT NULL,
  fk_prospectlevel varchar(12) DEFAULT NULL,
  fk_incoterms int DEFAULT NULL,
  location_incoterms varchar(255) DEFAULT NULL,
  customer_bad int DEFAULT '0',
  customer_rate float DEFAULT '0',
  supplier_rate float DEFAULT '0',
  remise_client float DEFAULT '0',
  remise_supplier float DEFAULT '0',
  mode_reglement int DEFAULT NULL,
  cond_reglement int DEFAULT NULL,
  transport_mode int DEFAULT NULL,
  mode_reglement_supplier int DEFAULT NULL,
  cond_reglement_supplier int DEFAULT NULL,
  transport_mode_supplier int DEFAULT NULL,
  fk_shipping_method int DEFAULT NULL,
  tva_assuj int DEFAULT '1',
  localtax1_assuj int DEFAULT '0',
  localtax1_value float DEFAULT NULL,
  localtax2_assuj int DEFAULT '0',
  localtax2_value float DEFAULT NULL,
  barcode varchar(180) DEFAULT NULL,
  fk_barcode_type int DEFAULT '0',
  price_level int DEFAULT NULL,
  outstanding_limit float DEFAULT NULL,
  order_min_amount float DEFAULT NULL,
  supplier_order_min_amount float DEFAULT NULL,
  default_lang varchar(6) DEFAULT NULL,
  logo varchar(255) DEFAULT NULL,
  logo_squarred varchar(255) DEFAULT NULL,
  canvas varchar(32) DEFAULT NULL,
  fk_warehouse int DEFAULT NULL,
  webservices_url varchar(255) DEFAULT NULL,
  webservices_key varchar(128) DEFAULT NULL,
  accountancy_code_sell varchar(32) DEFAULT NULL,
  accountancy_code_buy varchar(32) DEFAULT NULL,
  tms timestamp NOT NULL ,
  datec datetime DEFAULT NULL,
  fk_user_creat int DEFAULT NULL,
  fk_user_modif int DEFAULT NULL,
  fk_multicurrency int DEFAULT NULL,
  multicurrency_code varchar(255) DEFAULT NULL,
  import_key varchar(14) DEFAULT NULL,
  PRIMARY KEY (rowid),
  CONSTRAINT uk_societe_prefix_comm UNIQUE(prefix_comm,entity),
  CONSTRAINT uk_societe_code_client UNIQUE(code_client,entity),
  CONSTRAINT uk_societe_code_fournisseur UNIQUE(code_fournisseur,entity),
  CONSTRAINT uk_societe_barcode UNIQUE(barcode,fk_barcode_type,entity),
  CONSTRAINT idx_societe_user_creat UNIQUE(fk_user_creat),
  CONSTRAINT idx_societe_user_modif UNIQUE(fk_user_modif),
  CONSTRAINT idx_societe_stcomm UNIQUE(fk_stcomm),
  CONSTRAINT idx_societe_pays UNIQUE(fk_pays),
  CONSTRAINT idx_societe_account UNIQUE(fk_account),
  CONSTRAINT idx_societe_prospectlevel UNIQUE(fk_prospectlevel),
  CONSTRAINT idx_societe_typent UNIQUE(fk_typent),
  CONSTRAINT idx_societe_forme_juridique UNIQUE(fk_forme_juridique),
  CONSTRAINT idx_societe_shipping_method UNIQUE(fk_shipping_method)
)